choosing/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views

from polls import views as polls_views
from accounts import views as accounts_views

urlpatterns = [
    url(r'^$', polls_views.home, name='home'),
    url(r'^admin/', admin.site.urls),
    url(r'^login/$', auth_views.login),
    url(r'^logout/$', accounts_views.logout),
    url(r'^accounts/', include('authtools.urls')),
    url(r'^groups/$', accounts_views.index_group, name='index_group'),
    url(r'^groups/create/$', accounts_views.create_group, name='create_group'),
    url(r'^groups/(?P<group_id>[0-9]+)/$', accounts_views.detail_group, name='detail_group'),
    url(r'^polls/', include('polls.urls')),
    url(r'^venues/', include('venues.urls')),
    url(r'', include('social.apps.django_app.urls', namespace='social')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

polls/urls.py
from django.conf.urls import url

from . import views


app_name = 'polls'
urlpatterns = [
    url(r'^create/$', views.create, name='create'),
    url(r'^(?P<question_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
    url(r'^(?P<question_id>[0-9]+)/results/$', views.results, name='results'),
]

venues/urls.py
from django.conf.urls import url

from . import views


app_name = 'venues'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<venue_id>[0-9]+)/$', views.detail, name='detail'),
]

polls/models.py
from __future__ import absolute_import

from django.db import models
from django.db.models import Avg
from django_extensions.db.models import TimeStampedModel

from datetime import datetime

from accounts.models import User
from venues.models import Venue


class CurrentManager(models.Manager):
    def get_queryset(self):
        return super(CurrentManager, self).get_queryset().filter(created__date=datetime.today())


class PastManager(models.Manager):
    def get_queryset(self):
        return super(PastManager, self).get_queryset().filter(created__date__lt=datetime.today())


class Question(TimeStampedModel):
    objects = models.Manager()
    current = CurrentManager()
    past = PastManager()

    user = models.ForeignKey(User)
    completed = models.BooleanField(default=False)

    def get_question_venues(self):
        question_venues = []
        for question_venue in self.questionvenue_set.all():
            question_venues.append({
                'venue': question_venue.venue,
                'rating': question_venue.venuerating_set.all().aggregate(Avg('rating'))['rating__avg']})

        return question_venues

    question_venues = property(get_question_venues)

    def __str__(self):
        return "Question object: %d" % self.id


class Answer(TimeStampedModel):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    user = models.ForeignKey(User)

    def __str__(self):
        return "Answer object: %d" % self.id


class QuestionVenue(TimeStampedModel):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    venue = models.ForeignKey(Venue)

    def __str__(self):
        return self.venue.name


class VenueRating(TimeStampedModel):
    answer = models.ForeignKey(Answer, on_delete=models.CASCADE)
    question_venue = models.ForeignKey(QuestionVenue, on_delete=models.CASCADE)
    rating = models.FloatField()

    def __str__(self):
        return "VenueRating object: %d" % self.id

polls/views.py
from django.contrib.auth.decorators import login_required
from django.db.models import Avg
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.shortcuts import get_object_or_404, render
from django.template import loader
from django.urls import reverse

from accounts.models import User
from venues.models import Venue

from .models import Question, Answer, QuestionVenue, VenueRating


@login_required
def home(request):
    context = {}
    template = loader.get_template('polls/home.html')

    if request.user.is_authenticated():
        current_question_list = Question.current.all().filter(answer__user=request.user)
        past_question_list = Question.past.all().filter(answer__user=request.user)

        context.update({'current_question_list': current_question_list, 'past_question_list': past_question_list})

    return HttpResponse(template.render(context, request))


@login_required
def create(request):
    if request.method == 'GET':
        template = loader.get_template('polls/create.html')
        context = {}

        return HttpResponse(template.render(context, request))

    else:
        host = request.user
        users = request.POST.get('users').split(',')
        area = request.POST.get('area')
        category = request.POST.get('category')

        question = Question.objects.create(user=host)
        Answer.objects.bulk_create([Answer(question=question, user=User.objects.get(id=user)) for user in users])

        venues = Venue.objects.filter(address__contains=area)[:5]
        QuestionVenue.objects.bulk_create([QuestionVenue(question=question, venue=venue) for venue in venues])

        return HttpResponseRedirect(reverse('home'))


@login_required
def detail(request, question_id):
    try:
        question = Question.objects.get(pk=question_id)
        if question.completed:
            return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

    except Question.DoesNotExist:
        raise Http404("Question does not exist")

    return render(request, 'polls/detail.html', {'question': question})


@login_required
def results(request, question_id):
    try:
        question = Question.objects.get(pk=question_id)
        question_venues = []

        for question_venue in question.questionvenue_set.all():
            question_venues.append({
                'venue': question_venue.venue,
                'rating': question_venue.venuerating_set.all().aggregate(Avg('rating'))['rating__avg']})

    except Question.DoesNotExist:
        raise Http404("Question does not exist")

    return render(request, 'polls/results.html', {'question': question, 'question_venues': question_venues})


@login_required
def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)

    try:
        answer = Answer.objects.get(question=question, user=request.user)
        question_venues = [QuestionVenue.objects.get(id=question_venue) for question_venue in
                           request.POST.getlist('question_venues')]
        question_venues_with_rank = dict(zip(question_venues, request.POST.getlist('ranks')))

        VenueRating.objects.bulk_create([VenueRating(answer=answer, question_venue=qvwr[0], rating=qvwr[1])
                                         for qvwr in question_venues_with_rank.items()])

    except Exception as e:
        print("vote error: " + e)

    return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

polls/templates/polls/_home_poll_list.html
<ul>
    {% for question in past_question_list|dictsortreversed:"id" %}
        <li {% if forloop.last %} class='last'{% endif %}>
            <span>#{{ question.id }}</span>
            <a href="{% url 'polls:detail' question.id %}">
                {{ question.created|date:"m월 d일 (D)" }}
                {{ question.created|time:"H시 i분" }}
            </a>
            {% if question.completed %}
                {%  with question.question_venues|dictsortreversed:"rating"|first as first_qv %}
                    <p>{{ first_qv.venue.name }}
                    {{ first_qv.rating }} / 5.0</p>
                {% endwith %}
            {% else %}
                <div class="members">
                    {% for answer in question.answer_set.all %}
                        <img class="img-circle" src="{{ answer.user.picture.url }}" />
                    {% endfor %}
                </div>
            {% endif %}
        </li>
    {% endfor %}
</ul>

polls/templates/polls/create.html
{% extends 'base.html' %}

{% block content %}
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
<form action="{% url 'polls:create' %}" method="post">
    {% csrf_token %}
    <label for="users">User Ids</label>
    <input type="text" name="users" value="">
    <label for="area">Search Area</label>
    <input type="text" name="area" value="">
    <label for="category">Category</label>
    <input type="text" name="category" value="">
    <input type="submit" value="create">
</form>
{% endblock %}

polls/templates/polls/detail.html
{% extends 'base.html' %}

{% block content %}
    <p>{{ question.id }} Poll</p>

    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

    <form action="{% url 'polls:vote' question.id %}" method="post">
    {% csrf_token %}
    {% for question_venue in question.questionvenue_set.all %}
        <input type="text" name="ranks" id="question_venue{{ question_venue.id }}" required />
        <input type="hidden" name="question_venues" value="{{ question_venue.id }}" />
        <label for="question_venue{{ question_venue.id }}">{{ question_venue }}</label>
    {% endfor %}
    <input type="submit" value="vote" />
    </form>
{% endblock %}

polls/templates/polls/home.html
{% extends 'base.html' %}

{% block header %}
    {% load static %}
    <link href="{% static 'static/css/home.css' %}" rel="stylesheet" type="text/css">
{% endblock %}

{% block content %}
    <div class="profile">
        <div class="profile-row">
            <img class="img-circle" src="{{ request.user.picture.url }}" alt="user profile picture" />
            <div class="info">
                <p>{{ request.user.name }}</p>
                <a href="/groups/create/">My groups</a>
            </div>
        </div>
    </div>
    {% if not current_question_list and not past_question_list %}
        <div class="no_poll_list">
            <p>Choosing이 없는 계정입니다.</p>
            <a href="/polls/create/">Create a Choosing</a>
        </div>
    {% endif %}
    {% if current_question_list %}
        <div class="poll_list">
            <p class="section_title">Today Choosing</p>
            {% include '_home_poll_list.html' %}
        </div>
    {% endif %}
    {% if past_question_list %}
        <div class="poll_list">
            <p class="section_title">Past Choosing</p>
            {% include '_home_poll_list.html' %}
        </div>
    {% endif %}
{% endblock %}

{% block footer %}
    <a href="/polls/create/">Create a Choosing</a>
{% endblock %}

polls/templates/polls/index.html
{% extends 'base.html' %}

{% block content %}
    {% if question_list %}
        <ul>
            {% for question in question_list %}
                <li><a href="{% url 'polls:detail' question.id %}">#{{ question.id }} : {{ question.created }}</a></li>
            {% endfor %}
        </ul>
    {% else %}
        <p>No questions are available.</p>
    {% endif %}
{% endblock %}

polls/templates/polls/results.html
{% extends 'base.html' %}

{% block content %}
    <p>{{ question.id }} Poll Results</p>

    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

    {% for question_venue in question_venues|dictsortreversed:"rating" %}
        <a href="{% url 'venues:detail' question_venue.venue.id %}">{{ question_venue.venue.name }}</a>
        <p>{{ question_venue.rating }} / 5.0</p>
    {% endfor %}
{% endblock %}